### ISSUE TITLE
blank home directory in docker container

### ISSUE THREAD

**Issue by skomputer** [gansbrest/hodor#11]
Here is my .hodorfile

```
containers:
  littlesis:
    background: false
    image: littlesis/littlesis
    ports:
      - 80:80
      - 81:81
    onetime: true

tasks:
  littlesis:
    sync_project_to: /var/www/littlesis
    cmd: "cd /var/www/littlesis && bash"
    container: "littlesis"
```
When I run `hodor littlesis` it launches my container, but everything in my container's home directory (`/root`) is gone. I only see .bash_profile, .unison, etc.
