### ISSUE TITLE
Support for docker-compose

### ISSUE THREAD

**Issue by Maxim-Filimonov** [gansbrest/hodor#13]
Hey, 
Great tool but I already have a lot of configuration described in docker-compose yml for my local dev. Would be good to be able to use docker-compose with hodor instead of creating another configuration file for hodor specificially

**Comment by yvann** [comment]
+1 Ho yes, very good idea !

**Comment by noose** [comment]
+1

**Comment by wan54** [comment]
+1

**Comment by neolao** [comment]
+1

**Comment by mikeatlas** [comment]
hodor 

```yaml
host-manager: "docker-machine"
host: default

containers:
  <%= IO.readlines('./docker-compose.yml').join("\n  ") %>

tasks:
  up:
    sync_project_to: /data-dir
    cmd: "docker-compose"
    container: "docker_server"
  default: up
```

`hodor up`
