### ISSUE TITLE
How to specify volume share w/ Mac OSX host for `/data/db` directory of MongoDB container 

### ISSUE THREAD

**Issue by hironroy** [gansbrest/hodor#4]
Thanks for the great utility. Everything is working as advertised. However, I can't figure out how to define a volume for the [Mongo image](https://registry.hub.docker.com/_/mongo/) `data/db` directory through the `.hodorfile`. Currently, the MongoDB data persists until the `fileshare` container is closed, but once `fileshare` is closed, the data is lost. 

I'm running an _Express.js_ app backended to MongoDB and **would like to persist DB data beyond the life of the docker containers**. Before using Hodor, I accomplished this with this command: `docker run -d -p 27017:27017 -v `pwd`/tmp/data --name mongodb dockerfile/mongodb` (after having configured Virtual Box Guest Additions).

After unsuccessfully trying a number of options in `.hodorfile`, I started trying to find a relevant option in the source. Beyond the root level container (the one specified in the task), there isn't currently a way to define a `sync_to` for a given container is there?

Here is my `.hodorfile`. I launch it by executing `hodor npm start`. Any help would be greatly appreciated:

```
containers:
  mongodb:
    background: true
    image: mongo
    ports:
      - 27017:27017
    onetime: false
  expressExample:
    background: false
    image: dockerfile/nodejs-bower-grunt
    ports: 
      - 3000:3000
    links:
      mongodb: mongodb
    workdir: "/Users/hironroy/coding/moo/node-express-mongoose-demo"
    onetime: true
tasks:
  npm:
    sync_project_to: /Users/hironroy/coding/moo/node-express-mongoose-demo
    cmd: "cd /Users/hironroy/coding/moo/node-express-mongoose-demo && npm"
    container: "expressExample"
```

Thanks!
